# 与Spring结合的ActiveMQ才会使用此文件
server:
  port: 9090
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
    packages:
      trust-all: true
    pool:
      enabled: false
